---
 - hosts: GestionPersonas-v2
   user: azureuser
   become: yes
   tasks:
   
   - name: Instalar python 2.7.
     apt: pkg=python state=present

   - name: Instalar python 3.6.
     apt: pkg=python3.6 state=present

   - name: Instalar pip3.
     apt: pkg=python3-pip state=present

   - name: Instalar git.
     apt: pkg=git state=present

   - name: Instalar pipenv.
     shell: pip3 install pipenv

   - name: Instalar distutils.
     apt: pkg=python3-distutils state=present

   - name: Clonar proyecto.
     git: repo=https://github.com/mesagon/Proyecto-CC-MII.git dest=~/Proyecto-CC-MII force=yes

   - name: Establecer entorno virtual.
     shell: pipenv install
     args:
       chdir: ~/Proyecto-CC-MII

   - name: Ejecutar tests.
     shell: pipenv run python3 test/test.py
     args:
       chdir: ~/Proyecto-CC-MII

   - name: Desplegar aplicacion.
     shell: pipenv run gunicorn --reload -D -b 0.0.0.0:80 app:app
     args:
       chdir: ~/Proyecto-CC-MII
     
